variable "db_storage" { }
variable "db_name" { } 
variable "db_engineversion" { }
variable "db_instancetype" { }
variable "dbusername" { }
variable "dbpassword" { }
variable "snap" { }
variable "db_subnet_group_name" { }
variable "dbidentifier" { }
variable "vpc_security_group_ids" { }
